#!/usr/bin/env bash

# This is a shell wrapper for an awk script that requires two passes over a given stream.
# Currently using a tmp file but may want to 

if [ $# != 1 ]; then
	echo "Need one string for header field name." >&2
	exit 1
fi

header="$1";

cat > tmp

awk -v header="$header" 'BEGIN {
	FS = ",";
	max = 0 
}

FNR == NR {
	if (NF > max) {
		max = NF;
	}
	next;
}

FNR == 1 {
	for (i = 1; i <= max; i++) {
	       	printf header " " i FS;
	}

	printf ORS;
}

{
	printf $0;
	for (i = 0; i < max - NF; i++) {
	       	printf FS;
	}

	printf ORS;
}' tmp tmp

rm tmp
